### ISSUE TITLE
How to get mpv.app instead of just binary?

### ISSUE THREAD

**Issue by LampPrinter** [m154k1/mpv-build-macOS#2]
Like the title says. How do I get mpv.app not just binary?

**Comment by deus0ww** [comment]
https://github.com/mpv-player/mpv/wiki/Compiling-distro-releases-for-macOS

**Comment by LampPrinter** [comment]
Actually not standalone with all the libs included.
I just want .app, so it behaves like a normal MacOS app. Not having to open it from terminal and all.

Something easy like this
https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f

**Comment by deus0ww** [comment]
add --skip-deps to that python bundle command

**Comment by LampPrinter** [comment]
Running just `./TOOLS/osxbundle.py --skip-deps build/mpv`
-> FileNotFoundError: [Errno 2] No such file or directory: 'build/mpv'

Running the script in above link
-> /opt/homebrew/Cellar/libplacebo/6.338.1/include/libplacebo/vulkan.h:21:10: fatal error: 'vulkan/vulkan.h' file not found

```#!/usr/bin/env bash
set -ex

meson setup build
meson compile -C build
./build/mpv --version

./TOOLS/osxbundle.py --skip-deps build/mpv

**Comment by LampPrinter** [comment]
I have little knowledge of coding but I think something needs to be added to this file.

https://github.com/m154k1/mpv-build-macOS/blob/master/build-mpv

**Comment by deus0ww** [comment]
I really haven't installed it manually in a while....  if you like, you can try my homebrew-tap here: https://github.com/deus0ww/homebrew-tap

**Comment by LampPrinter** [comment]
I added these 2 lines

`cd src/mpv`
`./TOOLS/osxbundle.py --skip-deps /opt/local/mpv/bin/mpv`

 to the bottom of script
https://github.com/m154k1/mpv-build-macOS/blob/master/build-mpv

I am now getting an .app bundle.

**Comment by m154k1** [comment]
I never tried bundling mpv since I prefer CLI. But you're right, you need to run `osxbundle.py` and probably do code signing via `codesign`.

I think everything should be working except MoltenVK. Vulkan loader doesn't use traditional linking and loads `libMoltenVK.dylib` from path that set in ICD json file (`/opt/local/moltenvk/share/vulkan/icd.d/MoltenVK_icd.json`).

This might need to be adjusted too but I doubt it supports `@executable_path`, etc.:
https://github.com/m154k1/mpv-build-macOS/blob/fba5b8762c634b3e0441b0ee94b59c61d3166cc7/build-vulkan#L18-L21

**Comment by LampPrinter** [comment]
I am using --skip-deps. libs are not included in .app.
Will the above issue still be a problem?

On a separate note, everything seems to be working fine except there is a slight lag on opening a new file when using bluetooth earbuds. The video seems to jitter for a second on start.

**Comment by m154k1** [comment]
> I am using --skip-deps. libs are not included in .app.
> Will the above issue still be a problem?

Ah, I see. So the binary inside the app just uses dependencies from `/opt/local`. That's fine.

> everything seems to be working fine except there is a slight lag on opening a new file when using bluetooth earbuds

I guess that's expected. Bluetooth audio may have up to 200ms latency so mpv needs to wait a bit.

**Comment by deus0ww** [comment]
Try codesigning the bundle.  I find this solves a lot of strange behaviors especially on newer/current macOS.
